### ISSUE TITLE
Build failure with iOS project

### ISSUE THREAD

**Issue by lakario** [bitrise-steplib/steps-xamarin-builder#16]
As of the latest updates to this project (0.91), the build step for iOS cannot successfully compile my solution. I'm getting the following in the logs:

```
Loading solution: /Users/vagrant/git/src/Mobile/Mobile.sln
   Loading solution: /Users/vagrant/git/src/Mobile/Mobile.sln
      Loading projects ..
         WARNING: Error while trying to load the project '/Users/vagrant/git/src/Mobile/Mobile.iOS/Mobile.iOS.csproj': Object reference not set to an instance of an object
The project 'Mobile.iOS' could not be found in src/Mobile/Mobile.sln.
Build failed
ERRO[20:39:17] Step (xamarin-builder@1.0.1) failed, error: (exit status 1) 
```

This was not failing in the previous revision which I had been targeting.

**Comment by birmacher** [comment]
Hey @lakario!

We had a parsing issue with the platform and configuration mapping in the solution files. It should be resolved in 1.1.0.
If you hit the same issue again, please reopen the ticket.
