### ISSUE TITLE
outputs field is missing from step.yml

### ISSUE THREAD

**Issue by godrei** [bitrise-steplib/steps-xamarin-builder#21]
step generates the following outputs:
- BITRISE_APK_PATH
- BITRISE_IPA_PATH
- BITRISE_DSYM_PATH

These should be marked in step.yml too.

**Comment by birmacher** [comment]
Will be fixed in the next release - `1.1.4`.

I'll close this ticket later when it's released

**Comment by godrei** [comment]
solved in [v1.2.0](https://github.com/bitrise-steplib/steps-xamarin-builder/releases/tag/1.2.0)
