### ISSUE TITLE
Multiple iOS projects produce the same IPA filename

### ISSUE THREAD

**Issue by Qonstrukt** [bitrise-steplib/steps-xamarin-builder#22]
When building a solution with multiple iOS projects, the output filename always corresponds to the name of the Solution. This causes the IPA of the first iOS project to be overwritten by the second, etc.
I couldn't find a configuration in the step to prevent this. Also the Assembly name option in the Output settings of the project is ignored where this wasn't in the past. (I can't remember in which version this still worked correctly.)

**Comment by birmacher** [comment]
Hi @Qonstrukt!

Can you DM me on our slack channel ( http://chat.bitrise.io ), or follow-up through email at letsconnect@bitrise.io?
You can find me under the username @birmacher on Slack.

**Comment by birmacher** [comment]
I'm closing this issue now because it's a configuration issue, but to solve it simply update the `Bundle Name` of the apps to generate different IPA names.
