### ISSUE TITLE
No exportable output found

### ISSUE THREAD

**Issue by hvaughan3** [bitrise-steplib/steps-xamarin-builder#30]
Getting an error anytime I do a build saying **No exportable output found** with the Xamarin Builder then also **xamarin-builder (exit code: 1)**.

I do not see anything else obviously wrong in the logs. This solution use to build just fine. Also I am using the latest Xamarin Builder component (version 1.3.2). Please let me know what other info is needed. Thanks.

**Comment by godrei** [comment]
Hi @hvaughan3 
can you please attach your build log's xamarin-builder step part?

**Comment by hvaughan3** [comment]
@godrei Sure thing, should have done that to begin with.

Also, I can't be sure, but I feel like this started happening after I accidentally selected **Enabled NuGet Package Restore** of the solution. I tried undoing all of the changes that it makes but continue to get the error. Thank you and if there is anything I can do, please let me know. I already invited the **xamarin-support** user to my project on Bitrise.

[ac7dc7a6b02d9893.txt](https://github.com/bitrise-steplib/steps-xamarin-builder/files/331902/ac7dc7a6b02d9893.txt)

**Comment by godrei** [comment]
Your `debug|iPhoneSimulator` configuration creates an **.app** file which is used by **iPhoneSimulator**. Most of the times `iPhone` platform generates the desired **xcarchive**, which will be exported into an ios **.ipa file** by the step.

You should use the **same config|platform combination**, which you select in your **Xamarin IDE** and by clicking on Archive all will generate **ipa file**.

**Comment by hvaughan3** [comment]
@godrei You're awesome man. That worked perfectly and makes sense why it wasn't working. Really appreciate your help.

**Comment by godrei** [comment]
@hvaughan3 great to hear that! let us know if you need any help! 🚀
