### ISSUE TITLE
xamarin-builder@1.3.6 (exit code: 1)  

### ISSUE THREAD

**Issue by mrtnkrstn** [bitrise-steplib/steps-xamarin-builder#35]
Hi

I am getting the following build error on a Xamarin.iOS project:
# <RuntimeError: Build failed>

--- Stack trace: ---
["/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise500415748/step_src/xamarin-builder/builder.rb:36:in `block in build'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise500415748/step_src/xamarin-builder/builder.rb:31:in`each'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise500415748/step_src/xamarin-builder/builder.rb:31:in `build'", "/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise500415748/step_src/step.rb:312:in`<main>'"]

Not sure how to resolve it?

**Comment by godrei** [comment]
Hi @mrtnkrstn ,
to help you solve this issue, i will need your full failing build logs, to keep your data secure can you please write us on bitrise on-site-chat? just type in `xamarin-builder issue`, i will assign the conversation to me.

**Comment by godrei** [comment]
Issue is related to missing code sign files:

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets : error: iOS code signing key 'iPhone Developer: xyz' not found in keychain.`

Solution: upload code sign files to bitrise and build should work

Thanks for reporting!
