### ISSUE TITLE
Print the mdtool/xbuild command in copy-paste ready format

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-steplib/steps-xamarin-builder#37]
Right now it's printed as a Ruby array (`["xbuild", "/t:XyzAndroid", "/p:Configuration=\"Release\"", "\"./Path/To.csproj\"", "/verbosity:minimal", "/nologo"]`)

To conform to our other step outputs (and best practice) it should print it in a copy paste ready format, e.g.: `xbuild "/t:XyzAndroid" "/p:Configuration=\"Release\"" "./Path/To.csproj" "/verbosity:minimal" "/nologo"`

**Comment by godrei** [comment]
Hi @viktorbenei   

The new xamarin-archive step is available in the steplib. It prints the build commands in copy-paste ready format.

Like:

```
$ "/Library/Frameworks/Mono.framework/Commands/xbuild" "./_tmp/Multiplatform.sln" "/target:Build" "/p:SolutionDir=./_tmp" "/p:Configuration=Release" "/p:Platform=iPhone" "/p:ArchiveOnBuild=true" "/p:BuildIpa=true"
```

The blogpost about the new step and migration:
http://blog.bitrise.io/2016/10/18/the-new-xamarin-archive-step.html

**Comment by viktorbenei** [comment]
Thanks 👍 ;)
