### ISSUE TITLE
Use xbuild instead of mdtool

### ISSUE THREAD

**Issue by kevinmcmahon** [bitrise-steplib/steps-xamarin-builder#38]
@viktorbenei In issue #18 you mentioned that there are reasons for keeping mdtool around but I came across this post in Xamarin's bugzilla 
https://bugzilla.xamarin.com/show_bug.cgi?id=41011#c3 and was wondering if there were plans to migrate from mdtool to xbuild?

**Comment by godrei** [comment]
Hi @kevinmcmahon , 
we started to migrate to xbuild, it will take a couple of days to develop and test it.

In the first release we are planing to provide an input to force use mdtool, but by default xbuild will manage the builds.

**Comment by kevinmcmahon** [comment]
@godrei Thanks for the status update! Please let me know if you'd like help testing or verifying anything.

**Comment by godrei** [comment]
Hi @kevinmcmahon  

The new xamarin-archive step is available in the steplib. It uses xbuild by default for iOS, macOS and tvOS project, also have an input to switch back to mdtool.

The blogpost about the new step and migration:
http://blog.bitrise.io/2016/10/18/the-new-xamarin-archive-step.html
