### ISSUE TITLE
#<ArgumentError: invalid date> in Xamarin Builder

### ISSUE THREAD

**Issue by modplug** [bitrise-steplib/steps-xamarin-builder#41]
This happens when you try to build a Xamarin project on a PC with a date format different to US.

This line fails to parse the archive folder and the build fails.
https://github.com/bitrise-steplib/steps-xamarin-builder/blob/master/xamarin-builder/analyzer.rb#L857

**Comment by viktorbenei** [comment]
Thanks for reporting @modplug !

@godrei pls create an internal card for this ;)

**Comment by godrei** [comment]
Hi @modplug ,
could you please share an example layout of your archives folder path?

**Comment by godrei** [comment]
@modplug ,

The new xamarin-archive step is available in the steplib. It fixes this issue.

The blogpost about the new step and migration:
http://blog.bitrise.io/2016/10/18/the-new-xamarin-archive-step.html
