### ISSUE TITLE
Build failed for iOS if AssemlyName in csproj for iOS has spaces 

### ISSUE THREAD

**Issue by bykovme** [bitrise-steplib/steps-xamarin-builder#43]
I had the AssemblyName = "NS Wallet".
I changed the name to "NSWallet.iOS" and build succeeded. 

Could you fix it, so it is possible to have spaces in the name?
Thanks!

Bitrise gives the following error when failing:

> Exporting dSYM from archive at path /Users/vagrant/Library/Developer/Xcode/Archives/2016-09-30/NSWallet.iOS 9-30-16 6.16 AM.xcarchive
>   dSym found at path: /Users/vagrant/Library/Developer/Xcode/Archives/2016-09-30/NSWallet.iOS 9-30-16 6.16 AM.xcarchive/dSYMs/NS Wallet.app.dSYM
> 
> Generating archived dSYM from dSym: /Users/vagrant/Library/Developer/Xcode/Archives/2016-09-30/NSWallet.iOS 9-30-16 6.16 AM.xcarchive/dSYMs/NS Wallet.app.dSYM
>   zip warning: name not matched: Wallet.app.dSYM.zip
>   zip warning: name not matched: NS
>   zip warning: name not matched: Wallet.app.dSYM
> 
> zip error: Nothing to do! (try: zip -rTy /Users/vagrant/deploy/NS . -i Wallet.app.dSYM.zip NS Wallet.app.dSYM)
> Generating zip for dSym failed

**Comment by viktorbenei** [comment]
Thanks for reporting @bykovme !

@godrei please check this and schedule a fix (if not yet fixed)

**Comment by godrei** [comment]
Hi @bykovme ,

The new xamarin-archive step is available in the steplib. It fixes the issue with assembly name .

The blogpost about the new step and migration:
http://blog.bitrise.io/2016/10/18/the-new-xamarin-archive-step.html
