### ISSUE TITLE
Build failure caused by iOS Binding

### ISSUE THREAD

**Issue by lakario** [bitrise-steplib/steps-xamarin-builder#7]
Our Xamarin solution currently contains a Xamarin Binding project. This project is referenced by our main iOS project and is required for builds. When the xamarin-builder step processes the binding project, it compiles it successfully, and then produces a build failure due to there not being an IPA associated with the binding.

```
    Target DeployOutputFiles:
        Copying file from '/Users/vagrant/git/src/MobileLib/MobileLib.iOS.Binding/obj/Release/MobileLib.iOS.Binding.dll' to '/Users/vagrant/git/src/MobileLib/MobileLib.iOS.Binding/bin/AnyCPU/Release/MobileLib.iOS.Binding.dll'
Done building project "/Users/vagrant/git/src/MobileLib/MobileLib.iOS.Binding/MobileLib.iOS.Binding.csproj".
Build succeeded.
     0 Warning(s)
     0 Error(s)
Time Elapsed 00:00:04.3768540
No generated ipa file found
ERRO[22:43:45] Step (xamarin-builder@0.9.1) failed, error: (exit status 1) 
```

**Comment by lakario** [comment]
Based on what I can tell from the build script, it looks like all Xamarin.iOS projects are treated equally when building and archiving. There needs to be logic to check the project type, or perhaps output type, so that it can skip the call to [export_ipa() on line 93](https://github.com/bitrise-steplib/steps-xamarin-builder/blob/master/builder/builder.rb#L93)

**Comment by birmacher** [comment]
Hi @lakario!

Can you create a public git repository with an example project for this case? We are happy to fine-tune the step and solve the issue.
Till that I'll dig in, but it would make it easier to find the problem.

**Comment by lakario** [comment]
@birmacher Here you go: https://github.com/lakario/bitrise-xamarin-test.

**Comment by birmacher** [comment]
Thanks @lakario, we'll look into this.

**Comment by birmacher** [comment]
Thanks for all the help! I'm closing this because it's working now, but if you find out anything new, feel free to reopen it.
